In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import os
import sys
import matplotlib.pyplot as plt
from pathlib import Path
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

## Configure dependencies access

In [2]:
BASE_PATH = Path.cwd().parent.parent
ENV_PATH = BASE_PATH / "hospital_production" / ".env"

load_dotenv(ENV_PATH)

# PostgreSQL connection parameters
POSTGRES_USER: str = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD: str = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB: str = os.getenv("POSTGRES_DB")
POSTGRES_HOST: str = "localhost"
POSTGRES_PORT: str = os.getenv("POSTGRES_PORT")
POSTGRES_SCHEMA: str = os.getenv("POSTGRES_SCHEMA")
POSTGRES_TABLE: str = os.getenv("POSTGRES_TABLE")

# Build connection string
DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

# Create SQLAlchemy engine
engine = create_engine(DATABASE_URL)

# Open connection and execute query
with engine.connect() as conn:
    query = text(f"SELECT * FROM {POSTGRES_SCHEMA}.{POSTGRES_TABLE}")

    result = conn.execute(query)

    # Fetch and view the results into a pandas DataFrame
    df = pd.DataFrame(result.fetchall(), columns=result.keys())

In [3]:
pd.set_option('display.max_columns', None)
df.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction,month,week,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,total_staff,staff_present,staff_absens,length_of_stay,patient_churn,capacity_pressure,admission_rate_row,refusal_rate_row,staff_attendance_rate
0,PAT-f9c8afa6,Victor Baker,50,2025-07-30,2025-08-13,general_medicine,91,7,5,40,103.0,40.0,63.0,73.0,52.0,28,23.0,5.0,14,1,2.512195,0.388350,0.611650,0.821429
1,PAT-5290be70,Jeffrey Chandler,29,2025-11-01,2025-11-14,emergency,88,11,1,32,76.0,32.0,44.0,67.0,70.0,39,35.0,4.0,13,1,2.303030,0.421053,0.578947,0.897436
2,PAT-003ce690,Larry Dixon,29,2025-01-19,2025-01-21,ICU,60,1,3,20,21.0,20.0,1.0,82.0,89.0,34,0.0,34.0,2,1,1.000000,0.952381,0.047619,0.000000
3,PAT-18f78014,Kenneth Scott,77,2025-06-24,2025-06-26,general_medicine,61,6,4,43,152.0,43.0,109.0,67.0,66.0,28,22.0,6.0,2,1,3.454545,0.282895,0.717105,0.785714
4,PAT-69dc0dc1,April Frost,37,2025-11-15,2025-11-19,general_medicine,60,11,3,37,58.0,37.0,21.0,95.0,63.0,28,0.0,28.0,4,1,1.526316,0.637931,0.362069,0.000000

In [6]:
df.sample(10)

,patient_id,name,age,arrival_date,departure_date,service,satisfaction,month,week,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,total_staff,staff_present,staff_absens,length_of_stay,patient_churn,capacity_pressure,admission_rate_row,refusal_rate_row,staff_attendance_rate
4651,PAT-71899295,Derrick Bennett,40,2025-11-01,2025-11-13,general_medicine,69,11,1,42,124.56,45.78,41.62,80.21,71.75,28,8.59,9.17,12,0,2.896744,0.367534,0.334136,0.306786
1877,PAT-82335945,Bryan Webb,28,2025-01-04,2025-01-14,ICU,83,1,1,19,16.71,15.36,0.00,76.89,89.44,34,24.22,25.80,10,0,0.835500,0.919210,0.000000,0.712353
4227,PAT-f7bbd1f1,Virginia Hernandez,72,2025-10-23,2025-10-27,surgery,100,10,4,50,52.39,47.46,56.51,89.22,69.55,25,14.66,12.95,4,1,1.027255,0.905898,1.078641,0.586400
6174,PAT-c0c685d0,Tracie Thompson,25,2025-05-23,2025-06-02,ICU,90,5,4,17,25.41,16.25,3.19,81.86,88.35,34,37.08,14.99,10,0,1.411667,0.639512,0.125541,1.090588
2196,PAT-58250bf0,Heidi Patel,100,2025-01-22,2025-01-29,surgery,96,1,4,49,81.60,18.26,41.45,96.12,77.54,25,17.34,12.87,7,1,1.632000,0.223775,0.507966,0.693600
2062,PAT-df1d1938,Deborah Williams,18,2025-10-07,2025-10-18,surgery,73,10,1,39,0.00,53.47,95.44,89.05,86.44,25,0.00,4.97,11,1,0.000000,NaN,NaN,0.000000
8674,PAT-6892aa55,Patricia Lopez,56,2025-02-12,2025-02-17,general_medicine,78,2,2,40,148.89,43.48,126.11,82.66,93.82,28,24.39,1.60,5,1,3.631463,0.292028,0.847001,0.871071
8026,PAT-2c8c0f3b,John Campbell,37,2025-02-02,2025-02-08,general_medicine,71,2,1,42,215.59,37.27,96.80,96.95,54.77,28,15.04,1.02,6,1,5.013721,0.172874,0.449000,0.537143
8429,PAT-621eaff9,Heather Jackson,70,2025-09-22,2025-09-25,general_medicine,93,9,4,45,182.57,42.83,12.08,100.00,78.97,28,14.19,3.70,3,0,3.968913,0.234595,0.066166,0.506786
4159,PAT-8a41d923,Jennifer Harris,46,2025-10-26,2025-11-02,ICU,100,10,4,22,9.75,17.58,1.07,74.14,91.53,34,29.90,8.26,7,0,0.423913,1.803077,0.109744,0.879412

## Load new database parquet

In [ ]:
DATA_PARQUET = "../../hospital_production/database/Fix_final_2_database.parquet"

pd.set_option('display.max_columns', None)
df_2 = pd.read_parquet(DATA_PARQUET)
df_2

,patient_id,name,age,arrival_date,departure_date,service,satisfaction,month,week,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,total_staff,staff_present,staff_absens,length_of_stay,patient_churn,best_pred_churn,age_bin,staff_absent,arrival_year,arrival_month,arrival_week,arrival_dow,is_weekend,capacity_pressure,capacity_pressure_level,admission_rate_row,refusal_rate_row,staff_attendance_rate,_dissat,_los_risk,_refusal_pressure,_morale_risk,risk_score,risk_level,health_score
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61,3,3,27,66.00,27.00,39.00,63.00,72.00,25,0.00,25.00,6,1,1,19-35,25.00,2025,3,11,6,1,2.357143,High,0.409091,0.590909,0.000000,0.39,0.384615,0.590909,0.2800,41.233566,Medium,74.355371
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83,12,2,40,26.00,26.00,0.00,96.00,56.00,25,23.00,2.00,1,0,0,0-18,2.00,2025,12,50,5,1,0.634146,Low,1.000000,0.000000,0.920000,0.17,0.000000,0.000000,0.4400,13.400000,Low,74.355371
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83,6,5,40,103.00,40.00,63.00,73.00,52.00,28,23.00,5.00,6,1,1,19-35,5.00,2025,6,26,6,1,2.512195,High,0.388350,0.611650,0.821429,0.17,0.384615,0.611650,0.4800,35.848394,Medium,52.384121
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81,10,2,28,169.00,28.00,141.00,75.00,64.00,39,37.00,2.00,11,1,1,19-35,2.00,2025,10,41,6,1,5.827586,Critical,0.165680,0.834320,0.948718,0.19,0.769231,0.834320,0.3600,48.917160,Medium,48.986184
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76,2,3,20,21.00,20.00,1.00,82.00,89.00,34,0.00,34.00,7,0,0,19-35,34.00,2025,2,8,1,0,1.000000,Low,0.952381,0.047619,0.000000,0.24,0.461538,0.047619,0.1100,23.740842,Low,106.574244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,PAT-bc982acf,Michael Sparks,73,2025-03-09,2025-03-10,surgery,84,3,2,53,69.56,23.03,41.28,79.74,97.14,25,14.31,7.64,1,1,1,65+,7.64,2025,3,10,6,1,1.288148,Moderate,0.331081,0.593445,0.572400,0.16,0.000000,0.593445,0.0286,18.697890,Low,74.355371
9996,PAT-94ea6637,James Baker,24,2025-02-24,2025-03-08,emergency,81,2,4,29,122.29,30.06,109.46,65.76,73.29,39,48.14,16.79,12,1,1,19-35,16.79,2025,2,9,0,0,4.076333,Critical,0.245809,0.895085,1.234359,0.19,0.846154,0.895085,0.2671,50.662055,Medium,48.986184
9997,PAT-042af740,Ashley Gentry,78,2025-11-17,2025-11-22,ICU,83,11,3,19,20.71,10.77,4.51,73.55,87.58,34,40.45,0.00,5,0,0,65+,0.00,2025,11,47,0,0,1.035500,Moderate,0.520039,0.217769,1.189706,0.17,0.307692,0.217769,0.1242,20.710692,Low,106.574244
9998,PAT-6d3c54f9,Laura Rodgers,48,2025-03-09,2025-03-11,emergency,76,3,2,32,215.30,30.21,178.38,64.36,59.46,39,18.64,0.00,2,1,1,36-50,0.00,2025,3,10,6,1,6.524242,Critical,0.140316,0.828518,0.477949,0.24,0.076923,0.828518,0.4054,34.174444,Medium,48.986184
9999,PAT-f7220419,James Andrews,51,2025-01-01,2025-01-10,ICU,100,1,1,20,12.44,19.78,0.50,78.80,90.62,34,28.01,10.71,9,0,0,51-65,10.71,2025,1,1,2,0,0.592381,Low,1.590032,0.040193,0.823824,0.00,0.615385,0.040193,0.0938,17.595474,Low,106.574244

ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 302, in dispatch_control
    await self.process_control(msg)
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py", line 308, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/miftahhadiyannoor/Library/Python/3.11/lib/python/site-packages/jupyter_client/session.py", line 994, in feed_identities
    raise ValueError(msg)

In [19]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 40 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               10000 non-null  object
 1   name                     10000 non-null  object
 2   age                      10000 non-null  int64
 3   arrival_date             10000 non-null  datetime64[ns]
 4   departure_date           10000 non-null  datetime64[ns]
 5   service                  10000 non-null  object
 6   satisfaction             10000 non-null  int64
 7   month                    10000 non-null  int32
 8   week                     10000 non-null  int32
 9   available_beds           10000 non-null  int64
 10  patients_request         10000 non-null  float64
 11  patients_admitted        10000 non-null  float64
 12  patients_refused         10000 non-null  float64
 13  patient_satisfaction     10000 non-null  float64
 14  staff_morale             10000 non-null  float64
 15  total_staff              10000 non-null  int64
 16  staff_present            10000 non-null  float64
 17  staff_absens             10000 non-null  float64
 18  length_of_stay           10000 non-null  int64
 19  patient_churn            10000 non-null  int64
 20  best_pred_churn          10000 non-null  int64
 21  age_bin                  9593 non-null   category
 22  staff_absent             10000 non-null  float64
 23  arrival_year             10000 non-null  int32
 24  arrival_month            10000 non-null  int32
 25  arrival_week             10000 non-null  int64
 26  arrival_dow              10000 non-null  int32
 27  is_weekend               10000 non-null  int64
 28  capacity_pressure        10000 non-null  float64
 29  capacity_pressure_level  10000 non-null  category
 30  admission_rate_row       9867 non-null   float64
 31  refusal_rate_row         9867 non-null   float64
 32  staff_attendance_rate    10000 non-null  float64
 33  _dissat                  10000 non-null  float64
 34  _los_risk                10000 non-null  float64
 35  _refusal_pressure        10000 non-null  float64
 36  _morale_risk             10000 non-null  float64
 37  risk_score               10000 non-null  float64
 38  risk_level               10000 non-null  category
 39  health_score             10000 non-null  float64
dtypes: category(3), datetime64[ns](2), float64(18), int32(5), int64(9), object(3)
memory usage: 2.7+ MB

## Load ML Models from MinIO Bucket

In [24]:
from dotenv import load_dotenv
BASE_PATH = Path.cwd().parent.parent
ENV_PATH = BASE_PATH / "hospital_production" / ".env"
load_dotenv(ENV_PATH)

True

In [32]:
from minio import Minio
from minio.error import S3Error

# Intialize MinIO client
client = Minio(
    "localhost:9000",
    access_key=os.getenv("AWS_ACCESS_KEY_ID"),
    secret_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
    secure=False  # Set to True if using HTTPS
)

# Define bucket
bucket_name = "hospital-models"

try:
    objects = client.list_objects(bucket_name, recursive=True)

    print(f"Model found in bucket '{bucket_name}':")
    for obj in objects:
        print(f" - {obj.object_name}")

except S3Error as e:
    print(f"Error occurred: {e}")

Model found in bucket 'hospital-models':
 - manifest/integrity_audit.json
 - manifest/patient_churn.json
 - manifest/risk_level.json
 - manifest/risk_score.json
 - manifest/service_performance.json
 - manifest/staff_staff_attendance_rate.json
 - manifest/staff_staff_morale.json
 - mlflow/1/137ee340884442a3a4709a03addbd778/artifacts/manifest_patient_churn.json
 - mlflow/1/86df9eacc59448e9bf19e80f594256fc/artifacts/manifest_risk_score.json
 - mlflow/1/9dce29aeaa1b4ca989b5eebe3e3ea306/artifacts/manifest_risk_level.json
 - mlflow/1/a583e441f1854ba7bc7999648306dc02/artifacts/manifest_staff_staff_attendance_rate.json
 - mlflow/1/ad552a5926c94c16a52d6ee0bfc2b8bc/artifacts/manifest_staff_staff_morale.json
 - mlflow/1/d8aa349d747c405a8010ff4844039fa9/artifacts/manifest_service_performance.json
 - mlflow/1/eb8b7cc09b85488b830e232387e35045/artifacts/manifest_integrity_audit.json
 - mlflow/1/models/m-02dbdf35d0c345c9a5ec60af384ec796/artifacts/MLmodel
 - mlflow/1/models/m-02dbdf35d0c345c9a5ec60af384ec796/artifacts/conda.yaml
 - mlflow/1/models/m-02dbdf35d0c345c9a5ec60af384ec796/artifacts/model.skops
 - mlflow/1/models/m-02dbdf35d0c345c9a5ec60af384ec796/artifacts/python_env.yaml
 - mlflow/1/models/m-02dbdf35d0c345c9a5ec60af384ec796/artifacts/requirements.txt
 - mlflow/1/models/m-03b20ae0b230434da05b13959b0aef2c/artifacts/MLmodel
 - mlflow/1/models/m-03b20ae0b230434da05b13959b0aef2c/artifacts/conda.yaml
 - mlflow/1/models/m-03b20ae0b230434da05b13959b0aef2c/artifacts/model.skops
 - mlflow/1/models/m-03b20ae0b230434da05b13959b0aef2c/artifacts/python_env.yaml
 - mlflow/1/models/m-03b20ae0b230434da05b13959b0aef2c/artifacts/requirements.txt
 - mlflow/1/models/m-05818271c12540d2a5dd5ccc6da43320/artifacts/MLmodel
 - mlflow/1/models/m-05818271c12540d2a5dd5ccc6da43320/artifacts/conda.yaml
 - mlflow/1/models/m-05818271c12540d2a5dd5ccc6da43320/artifacts/model.skops
 - mlflow/1/models/m-05818271c12540d2a5dd5ccc6da43320/artifacts/python_env.yaml
 - mlflow/1/models/m-05818271c12540d2a5dd5ccc6da43320/artifacts/requirements.txt
 - mlflow/1/models/m-094e3d72c836451dbaf50b81d21fa9d7/artifacts/MLmodel
 - mlflow/1/models/m-094e3d72c836451dbaf50b81d21fa9d7/artifacts/conda.yaml
 - mlflow/1/models/m-094e3d72c836451dbaf50b81d21fa9d7/artifacts/model.skops
 - mlflow/1/models/m-094e3d72c836451dbaf50b81d21fa9d7/artifacts/python_env.yaml
 - mlflow/1/models/m-094e3d72c836451dbaf50b81d21fa9d7/artifacts/requirements.txt
 - mlflow/1/models/m-1f115f28bd87429daae7df73dfa9f878/artifacts/MLmodel
 - mlflow/1/models/m-1f115f28bd87429daae7df73dfa9f878/artifacts/conda.yaml
 - mlflow/1/models/m-1f115f28bd87429daae7df73dfa9f878/artifacts/model.skops
 - mlflow/1/models/m-1f115f28bd87429daae7df73dfa9f878/artifacts/python_env.yaml
 - mlflow/1/models/m-1f115f28bd87429daae7df73dfa9f878/artifacts/requirements.txt
 - mlflow/1/models/m-26010904be3e4776bade60b823073668/artifacts/MLmodel
 - mlflow/1/models/m-26010904be3e4776bade60b823073668/artifacts/conda.yaml
 - mlflow/1/models/m-26010904be3e4776bade60b823073668/artifacts/model.skops
 - mlflow/1/models/m-26010904be3e4776bade60b823073668/artifacts/python_env.yaml
 - mlflow/1/models/m-26010904be3e4776bade60b823073668/artifacts/requirements.txt
 - mlflow/1/models/m-2d415c51144a4ebc9f2fe3f9d509550f/artifacts/MLmodel
 - mlflow/1/models/m-2d415c51144a4ebc9f2fe3f9d509550f/artifacts/conda.yaml
 - mlflow/1/models/m-2d415c51144a4ebc9f2fe3f9d509550f/artifacts/model.skops
 - mlflow/1/models/m-2d415c51144a4ebc9f2fe3f9d509550f/artifacts/python_env.yaml
 - mlflow/1/models/m-2d415c51144a4ebc9f2fe3f9d509550f/artifacts/requirements.txt
 - mlflow/1/models/m-304f54d0edc64cc186db72bf63d9aeee/artifacts/MLmodel
 - mlflow/1/models/m-304f54d0edc64cc186db72bf63d9aeee/artifacts/conda.yaml
 - mlflow/1/models/m-304f54d0edc64cc186db72bf63d9aeee/artifacts/model.skops
 - mlflow/1/models/m-304f54d0edc64cc186db72bf63d9aeee/artifacts/python_env.yaml
 - mlflow/1/models/m-304f54d0edc64cc186db72bf63d9aeee/artifacts/requirements.txt
 - mlflow/1/models/m-367f09125d5d45d99e8ff7e88dfa86eb/artifacts/MLmodel
 - mlflow/1/models/m-367f09125d5d45d99e8ff7e88dfa86eb/artifacts/conda.yaml
 - mlflow/1/models/m-367f09125d5d45d99e8ff7e88dfa86eb/artifacts/model.skops
 - mlflow/1/models/m-367f09125d5d45d99e8ff7e88dfa86eb/artifacts/python_env.yaml
 - mlflow/1/models/m-367f09125d5d45d99e8ff7e88dfa86eb/artifacts/requirements.txt
 - mlflow/1/models/m-4515fd0723ad455e911efdc31c897679/artifacts/MLmodel
 - mlflow/1/models/m-4515fd0723ad455e911efdc31c897679/artifacts/conda.yaml
 - mlflow/1/models/m-4515fd0723ad455e911efdc31c897679/artifacts/model.skops
 - mlflow/1/models/m-4515fd0723ad455e911efdc31c897679/artifacts/python_env.yaml
 - mlflow/1/models/m-4515fd0723ad455e911efdc31c897679/artifacts/requirements.txt
 - mlflow/1/models/m-4710051c12384ab89dd6cf5a138f11d8/artifacts/MLmodel
 - mlflow/1/models/m-4710051c12384ab89dd6cf5a138f11d8/artifacts/conda.yaml
 - mlflow/1/models/m-4710051c12384ab89dd6cf5a138f11d8/artifacts/model.skops
 - mlflow/1/models/m-4710051c12384ab89dd6cf5a138f11d8/artifacts/python_env.yaml
 - mlflow/1/models/m-4710051c12384ab89dd6cf5a138f11d8/artifacts/requirements.txt
 - mlflow/1/models/m-4ba5923f29ad4784b21e86cdff7dc112/artifacts/MLmodel
 - mlflow/1/models/m-4ba5923f29ad4784b21e86cdff7dc112/artifacts/conda.yaml
 - mlflow/1/models/m-4ba5923f29ad4784b21e86cdff7dc112/artifacts/model.skops
 - mlflow/1/models/m-4ba5923f29ad4784b21e86cdff7dc112/artifacts/python_env.yaml
 - mlflow/1/models/m-4ba5923f29ad4784b21e86cdff7dc112/artifacts/requirements.txt
 - mlflow/1/models/m-4f5f341de9b94e41b151c7e20cf316df/artifacts/MLmodel
 - mlflow/1/models/m-4f5f341de9b94e41b151c7e20cf316df/artifacts/conda.yaml
 - mlflow/1/models/m-4f5f341de9b94e41b151c7e20cf316df/artifacts/model.skops
 - mlflow/1/models/m-4f5f341de9b94e41b151c7e20cf316df/artifacts/python_env.yaml
 - mlflow/1/models/m-4f5f341de9b94e41b151c7e20cf316df/artifacts/requirements.txt
 - mlflow/1/models/m-5e3731eec57949bebbdb9b975a037069/artifacts/MLmodel
 - mlflow/1/models/m-5e3731eec57949bebbdb9b975a037069/artifacts/conda.yaml
 - mlflow/1/models/m-5e3731eec57949bebbdb9b975a037069/artifacts/model.skops
 - mlflow/1/models/m-5e3731eec57949bebbdb9b975a037069/artifacts/python_env.yaml
 - mlflow/1/models/m-5e3731eec57949bebbdb9b975a037069/artifacts/requirements.txt
 - mlflow/1/models/m-709aab6a18084b86b77b3c9b3fbedccf/artifacts/MLmodel
 - mlflow/1/models/m-709aab6a18084b86b77b3c9b3fbedccf/artifacts/conda.yaml
 - mlflow/1/models/m-709aab6a18084b86b77b3c9b3fbedccf/artifacts/model.skops
 - mlflow/1/models/m-709aab6a18084b86b77b3c9b3fbedccf/artifacts/python_env.yaml
 - mlflow/1/models/m-709aab6a18084b86b77b3c9b3fbedccf/artifacts/requirements.txt
 - mlflow/1/models/m-7a88f4ba504346479adbe2ae78dd307c/artifacts/MLmodel
 - mlflow/1/models/m-7a88f4ba504346479adbe2ae78dd307c/artifacts/conda.yaml
 - mlflow/1/models/m-7a88f4ba504346479adbe2ae78dd307c/artifacts/model.skops
 - mlflow/1/models/m-7a88f4ba504346479adbe2ae78dd307c/artifacts/python_env.yaml
 - mlflow/1/models/m-7a88f4ba504346479adbe2ae78dd307c/artifacts/requirements.txt
 - mlflow/1/models/m-7b597315b238429dacc1d53e2bdc51f3/artifacts/MLmodel
 - mlflow/1/models/m-7b597315b238429dacc1d53e2bdc51f3/artifacts/conda.yaml
 - mlflow/1/models/m-7b597315b238429dacc1d53e2bdc51f3/artifacts/model.skops
 - mlflow/1/models/m-7b597315b238429dacc1d53e2bdc51f3/artifacts/python_env.yaml
 - mlflow/1/models/m-7b597315b238429dacc1d53e2bdc51f3/artifacts/requirements.txt
 - mlflow/1/models/m-829498deecf34856b13ad72d42233f03/artifacts/MLmodel
 - mlflow/1/models/m-829498deecf34856b13ad72d42233f03/artifacts/conda.yaml
 - mlflow/1/models/m-829498deecf34856b13ad72d42233f03/artifacts/model.skops
 - mlflow/1/models/m-829498deecf34856b13ad72d42233f03/artifacts/python_env.yaml
 - mlflow/1/models/m-829498deecf34856b13ad72d42233f03/artifacts/requirements.txt
 - mlflow/1/models/m-83ef96a656d94a05b1556a65692a7ca9/artifacts/MLmodel
 - mlflow/1/models/m-83ef96a656d94a05b1556a65692a7ca9/artifacts/conda.yaml
 - mlflow/1/models/m-83ef96a656d94a05b1556a65692a7ca9/artifacts/model.skops
 - mlflow/1/models/m-83ef96a656d94a05b1556a65692a7ca9/artifacts/python_env.yaml
 - mlflow/1/models/m-83ef96a656d94a05b1556a65692a7ca9/artifacts/requirements.txt
 - mlflow/1/models/m-8ac1bf140fe04935b955611aa28c12d9/artifacts/MLmodel
 - mlflow/1/models/m-8ac1bf140fe04935b955611aa28c12d9/artifacts/conda.yaml
 - mlflow/1/models/m-8ac1bf140fe04935b955611aa28c12d9/artifacts/model.skops
 - mlflow/1/models/m-8ac1bf140fe04935b955611aa28c12d9/artifacts/python_env.yaml
 - mlflow/1/models/m-8ac1bf140fe04935b955611aa28c12d9/artifacts/requirements.txt
 - mlflow/1/models/m-a0455db339b64121929f3c023e5e6399/artifacts/MLmodel
 - mlflow/1/models/m-a0455db339b64121929f3c023e5e6399/artifacts/conda.yaml
 - mlflow/1/models/m-a0455db339b64121929f3c023e5e6399/artifacts/model.skops
 - mlflow/1/models/m-a0455db339b64121929f3c023e5e6399/artifacts/python_env.yaml
 - mlflow/1/models/m-a0455db339b64121929f3c023e5e6399/artifacts/requirements.txt
 - mlflow/1/models/m-a3f58a199207479b845b60c7a3f507a0/artifacts/MLmodel
 - mlflow/1/models/m-a3f58a199207479b845b60c7a3f507a0/artifacts/conda.yaml
 - mlflow/1/models/m-a3f58a199207479b845b60c7a3f507a0/artifacts/model.skops
 - mlflow/1/models/m-a3f58a199207479b845b60c7a3f507a0/artifacts/python_env.yaml
 - mlflow/1/models/m-a3f58a199207479b845b60c7a3f507a0/artifacts/requirements.txt
 - mlflow/1/models/m-a61f651fb24a42bdac8080f77bd6c53f/artifacts/MLmodel
 - mlflow/1/models/m-a61f651fb24a42bdac8080f77bd6c53f/artifacts/conda.yaml
 - mlflow/1/models/m-a61f651fb24a42bdac8080f77bd6c53f/artifacts/model.skops
 - mlflow/1/models/m-a61f651fb24a42bdac8080f77bd6c53f/artifacts/python_env.yaml
 - mlflow/1/models/m-a61f651fb24a42bdac8080f77bd6c53f/artifacts/requirements.txt
 - mlflow/1/models/m-a8762f79372344c6b084bcf5925751f6/artifacts/MLmodel
 - mlflow/1/models/m-a8762f79372344c6b084bcf5925751f6/artifacts/conda.yaml
 - mlflow/1/models/m-a8762f79372344c6b084bcf5925751f6/artifacts/model.skops
 - mlflow/1/models/m-a8762f79372344c6b084bcf5925751f6/artifacts/python_env.yaml
 - mlflow/1/models/m-a8762f79372344c6b084bcf5925751f6/artifacts/requirements.txt
 - mlflow/1/models/m-a9730a0800f64b7cb4ca69d351ff4831/artifacts/MLmodel
 - mlflow/1/models/m-a9730a0800f64b7cb4ca69d351ff4831/artifacts/conda.yaml
 - mlflow/1/models/m-a9730a0800f64b7cb4ca69d351ff4831/artifacts/model.skops
 - mlflow/1/models/m-a9730a0800f64b7cb4ca69d351ff4831/artifacts/python_env.yaml
 - mlflow/1/models/m-a9730a0800f64b7cb4ca69d351ff4831/artifacts/requirements.txt
 - mlflow/1/models/m-b40ec19494814bdc9ab243fc663b7f97/artifacts/MLmodel
 - mlflow/1/models/m-b40ec19494814bdc9ab243fc663b7f97/artifacts/conda.yaml
 - mlflow/1/models/m-b40ec19494814bdc9ab243fc663b7f97/artifacts/model.skops
 - mlflow/1/models/m-b40ec19494814bdc9ab243fc663b7f97/artifacts/python_env.yaml
 - mlflow/1/models/m-b40ec19494814bdc9ab243fc663b7f97/artifacts/requirements.txt
 - mlflow/1/models/m-bc6450c238824c52969ed2c32d3b7f1a/artifacts/MLmodel
 - mlflow/1/models/m-bc6450c238824c52969ed2c32d3b7f1a/artifacts/conda.yaml
 - mlflow/1/models/m-bc6450c238824c52969ed2c32d3b7f1a/artifacts/model.skops
 - mlflow/1/models/m-bc6450c238824c52969ed2c32d3b7f1a/artifacts/python_env.yaml
 - mlflow/1/models/m-bc6450c238824c52969ed2c32d3b7f1a/artifacts/requirements.txt
 - mlflow/1/models/m-bd6203d913304526b6752f89f863bc1c/artifacts/MLmodel
 - mlflow/1/models/m-bd6203d913304526b6752f89f863bc1c/artifacts/conda.yaml
 - mlflow/1/models/m-bd6203d913304526b6752f89f863bc1c/artifacts/model.skops
 - mlflow/1/models/m-bd6203d913304526b6752f89f863bc1c/artifacts/python_env.yaml
 - mlflow/1/models/m-bd6203d913304526b6752f89f863bc1c/artifacts/requirements.txt
 - mlflow/1/models/m-c076d269209247129e476763751a216c/artifacts/MLmodel
 - mlflow/1/models/m-c076d269209247129e476763751a216c/artifacts/conda.yaml
 - mlflow/1/models/m-c076d269209247129e476763751a216c/artifacts/model.skops
 - mlflow/1/models/m-c076d269209247129e476763751a216c/artifacts/python_env.yaml
 - mlflow/1/models/m-c076d269209247129e476763751a216c/artifacts/requirements.txt
 - mlflow/1/models/m-cacbc5cfe75c4fd2afa005abfc27afee/artifacts/MLmodel
 - mlflow/1/models/m-cacbc5cfe75c4fd2afa005abfc27afee/artifacts/conda.yaml
 - mlflow/1/models/m-cacbc5cfe75c4fd2afa005abfc27afee/artifacts/model.skops
 - mlflow/1/models/m-cacbc5cfe75c4fd2afa005abfc27afee/artifacts/python_env.yaml
 - mlflow/1/models/m-cacbc5cfe75c4fd2afa005abfc27afee/artifacts/requirements.txt
 - mlflow/1/models/m-e2415b91b908464296a2c69dc9e2c6f6/artifacts/MLmodel
 - mlflow/1/models/m-e2415b91b908464296a2c69dc9e2c6f6/artifacts/conda.yaml
 - mlflow/1/models/m-e2415b91b908464296a2c69dc9e2c6f6/artifacts/model.skops
 - mlflow/1/models/m-e2415b91b908464296a2c69dc9e2c6f6/artifacts/python_env.yaml
 - mlflow/1/models/m-e2415b91b908464296a2c69dc9e2c6f6/artifacts/requirements.txt
 - mlflow/1/models/m-e8fe89a3666e4903911b383303927f40/artifacts/MLmodel
 - mlflow/1/models/m-e8fe89a3666e4903911b383303927f40/artifacts/conda.yaml
 - mlflow/1/models/m-e8fe89a3666e4903911b383303927f40/artifacts/model.skops
 - mlflow/1/models/m-e8fe89a3666e4903911b383303927f40/artifacts/python_env.yaml
 - mlflow/1/models/m-e8fe89a3666e4903911b383303927f40/artifacts/requirements.txt
 - mlflow/1/models/m-ecb49d26f0e24cd288ab519df8d3956f/artifacts/MLmodel
 - mlflow/1/models/m-ecb49d26f0e24cd288ab519df8d3956f/artifacts/conda.yaml
 - mlflow/1/models/m-ecb49d26f0e24cd288ab519df8d3956f/artifacts/model.skops
 - mlflow/1/models/m-ecb49d26f0e24cd288ab519df8d3956f/artifacts/python_env.yaml
 - mlflow/1/models/m-ecb49d26f0e24cd288ab519df8d3956f/artifacts/requirements.txt
 - mlflow/1/models/m-fa6b6603fd8343f9adbaf24dfa15ee9a/artifacts/MLmodel
 - mlflow/1/models/m-fa6b6603fd8343f9adbaf24dfa15ee9a/artifacts/conda.yaml
 - mlflow/1/models/m-fa6b6603fd8343f9adbaf24dfa15ee9a/artifacts/model.skops
 - mlflow/1/models/m-fa6b6603fd8343f9adbaf24dfa15ee9a/artifacts/python_env.yaml
 - mlflow/1/models/m-fa6b6603fd8343f9adbaf24dfa15ee9a/artifacts/requirements.txt
 - mlflow/1/models/m-feeaeb64ddc940b79fa678ae204eadb9/artifacts/MLmodel
 - mlflow/1/models/m-feeaeb64ddc940b79fa678ae204eadb9/artifacts/conda.yaml
 - mlflow/1/models/m-feeaeb64ddc940b79fa678ae204eadb9/artifacts/model.skops
 - mlflow/1/models/m-feeaeb64ddc940b79fa678ae204eadb9/artifacts/python_env.yaml
 - mlflow/1/models/m-feeaeb64ddc940b79fa678ae204eadb9/artifacts/requirements.txt
 - models/integrity_audit_bundle.joblib
 - models/patient_churn_bundle.joblib
 - models/risk_level_bundle.joblib
 - models/risk_score_bundle.joblib
 - models/service_performance_bundle.joblib
 - models/staff_staff_attendance_rate_bundle.joblib
 - models/staff_staff_morale_bundle.joblib

In [33]:
# Retrieve only models/ name in bucket
ml_models = [obj.object_name for obj in client.list_objects(bucket_name, recursive=True) if obj.object_name.startswith("models/")]
ml_models

['models/integrity_audit_bundle.joblib',
 'models/patient_churn_bundle.joblib',
 'models/risk_level_bundle.joblib',
 'models/risk_score_bundle.joblib',
 'models/service_performance_bundle.joblib',
 'models/staff_staff_attendance_rate_bundle.joblib',
 'models/staff_staff_morale_bundle.joblib']

## Implemented models:
* ### Return to A/B Testing
* ### Implementation models to database and return the result